import { htmlEncode, htmlDecode } from "js-htmlencode";

const pkg = require("../../package.json");
const isPreview = pkg.version.indexOf("preview") != -1;
const isDev = pkg.name.indexOf("dev") != -1;

export const _data = {
    "zh-cn": {
        "com_unknown": "无法在语言文件中找到此条目的本地化文本。",
        "com_name": ((!isDev) ? ((!isPreview) ? ("Platinum") : ("Platinum 预览版")) : ("Platinum 开发版")),
        "com_author": "Flysoft",
        "com_remove": "移除",
        "com_delete": "删除",
        "com_edit": "编辑",
        "com_ok": "确定",
        "com_cancel": "取消",
        "com_trash": "将文件移入垃圾桶",
        "com_continue": "继续",
        "com_pause": "暂停",
        "com_redownload": "重新下载",
        "com_remove_result": "移除下载记录",
        "com_new_tab": "新标签页",
        "com_create_tab": "创建新标签页",
        "com_undo": "撤销",
        "com_redo": "恢复",
        "com_cut": "剪切",
        "com_copy": "复制",
        "com_paste": "粘贴",
        "com_paste_text": "粘贴为纯文本",
        "com_selectall": "全选",
        "com_tab_close": "关闭标签页",
        "com_nav_back": "后退",
        "com_nav_forward": "前进",
        "com_nav_refresh": "刷新",
        "com_nav_stop": "停止加载",
        "com_nav_home": "主页",
        "com_nav_urlinput": "URL",
        "com_nav_fav_add": "将此网页添加到收藏夹中",
        "com_nav_fav_remove": "将此网页从收藏夹中移除",
        "com_nav_more": "更多",
        "com_nav_siteinfo_safe": "连接是安全的，点击查看更多站点信息",
        "com_nav_siteinfo_unsafe": "您到此网站的连接不是私密连接，点击查看更多站点信息",
        "com_nav_siteinfo_internal": "您正在查看一个安全的 [use_com_name] 页面",
        "com_nav_siteinfo_file": "您正在查看一个本地页面",
        "com_nav_siteinfo_unknown": "此站点的协议未知",
        "com_select_file": "选择一个文件",
        "com_whatsnew": "查看新增功能",
        "start_title": "开始",
        "start_settings": "\"开始\" 页面设置",
        "start_search": "搜索或输入 URL",
        "his_title": "历史记录",
        "his_all": "全部",
        "his_removemulti_title": "已选择 [0] 个项目。",
        "ups_title": "[use_com_name] 已更新!",
        "ups_body": "您的浏览器已经成功升级到 [0]。",
        "cl_title": "更新日志",
        "tetris_title": "俄罗斯方块",
        "tetris_score": "分数: [0]",
        "tetris_gameover": "按下空格键重新开始",
        "siteinfo_safe": "连接安全\n这意味着您的信息会被加密地发送至网站，且不会被攻击者盗取。(但这并不意味着这个网站是安全的。)",
        "siteinfo_unsafe": "您到此网站的连接不是私密连接\n请勿在此网站上输入任何敏感信息 (例如密码或银行卡)，因为可能会被攻击者盗取。",
        "siteinfo_show_cert": "查看站点证书",
        "set_title": "设置",
        "set_needrestart_title": "[use_com_name] 需要重启",
        "set_needrestart_settings_body": "你所更改的设置需要重启浏览器才能生效。\n点此重启浏览器。",
        "set_needrestart_update_body": "更新下载完毕，请重启浏览器来应用更新。\n点此重启浏览器。",
        "set_user": "用户",
        "set_user_sync": "数据同步",
        "set_user_sync_enable": "启用同步",
        "set_user_sync_token": "GitHub Access Token",
        "set_user_sync_token_info_part1": "我们需要访问您的 GitHub Gist 才能开启同步。请生成一个 ",
        "set_user_sync_token_info_part2": "GitHub Access Token",
        "set_user_sync_token_info_part3": " 并粘贴到上方的输入框中即可开启同步。",
        "set_user_other": "其他",
        "set_user_other_desktoplink": "创建桌面快捷方式",
        "set_user_other_edit": "编辑用户信息",
        "set_user_other_delete": "删除此用户",
        "set_homepage": "主页",
        "set_homepage_start": "开始",
        "set_homepage_start_background": "背景图片",
        "set_homepage_start_background_unsplash": "从 Unsplash 随机获取",
        "set_homepage_start_background_bing": "从必应每日一图获取",
        "set_homepage_start_background_pixiv": "获取 Pixiv 上的随机图片 (第三方)",
        "set_homepage_start_background_genshin": "获取原神随机图片 (第三方)",
        "set_homepage_start_background_honkai": "获取崩坏3随机图片 (第三方)",
        "set_homepage_start_background_mc": "获取 Minecraft 随机图片 (第三方)",
        "set_homepage_start_background_url": "从 URL 获取",
        "set_homepage_start_background_file": "本地图像",
        "set_homepage_start_background_no": "关闭背景图片",
        "set_homepage_start_background_info_pixiv_part1": "Pixiv 随机图片服务",
        "set_homepage_start_background_info_pixiv_part2": "Lolicon API",
        "set_homepage_start_background_info_horatio_part1": "原神、崩坏3、Minecraft 随机图片服务",
        "set_homepage_start_background_info_horatio_part2": "HoratioWeb",
        "set_homepage_start_background_info_part1": "由 ",
        "set_homepage_start_background_info_part2": " 提供，",
        "set_homepage_start_background_info_part3": "与 [use_com_author] 没有任何关系 (注: API 提供的图片可能包含二创内容，请谨慎使用)。",
        "set_homepage_start_background_blur": "启用背景模糊",
        "set_homepage_home": "主页",
        "set_homepage_homebtn_show": "显示主页按钮",
        "set_homepage_page": "主页网址",
        "set_homepage_page_start": "使用开始页面",
        "set_homepage_page_url": "使用自定义 URL",
        "set_appearance": "外观",
        "set_appearance_overall": "整体外观",
        "set_appearance_overall_default": "跟随系统",
        "set_appearance_overall_light": "亮色",
        "set_appearance_overall_dark": "暗色",
        "set_appearance_theme": "主题",
        "set_appearance_visual": "视觉效果",
        "set_appearance_visual_blur": "启用模糊效果",
        "set_appearance_visual_fullblur": "启用全模糊效果",
        "set_appearance_visual_usebackdrop": "使用系统的模糊效果代替软件自带的模糊效果 (实验性)",
        "set_appearance_visual_spotlight": "启用聚光灯效果 (实验性)",
        "set_appearance_visual_animation": "禁用动画效果",
        "set_appearance_visual_lowperformance": "启用流畅模式",
        "set_appearance_visual_lowperformance_info": "去除部分影响性能的效果与动画，该选项对性能不佳的电脑十分有用。",
        "set_appearance_tcolor": "主题色",
        "set_appearance_tcolor_system": "使用系统主题色",
        "set_appearance_tcolor_theme": "使用主题指定的主题色",
        "set_appearance_tcolor_custom": "使用自定义主题色",
        "set_appearance_behavior": "浏览器行为",
        "set_appearance_behavior_askmulti": "关闭包含多个标签页的窗口前进行询问",
        "set_pfm": "性能",
        "set_pfm_sys": "系统",
        "set_pfm_sys_turbo": "启动加速",
        "set_pfm_sys_turbo_info": "在后台启动 [use_com_name] 以便更快地打开窗口。",
        "set_pfm_sys_hardwareacceleration": "启用硬件加速",
        "set_pfm_sleep": "标签页睡眠",
        "set_pfm_sleep_enable": "启用标签页睡眠",
        "set_pfm_sleep_enable_info": "长时间未使用的标签页会自动进入睡眠模式，减少 CPU 占用。",
        "set_pfm_sleep_timeout": "当标签页未使用多久时，让标签页进入睡眠模式",
        "set_pfm_sleep_timeout_immediately": "立刻",
        "set_pfm_sleep_timeout_1min": "1 分钟",
        "set_pfm_sleep_timeout_10min": "10 分钟",
        "set_pfm_sleep_timeout_30min": "30 分钟",
        "set_pfm_sleep_timeout_1hour": "1 小时",
        "set_pfm_sleep_timeout_2hour": "2 小时",
        "set_language": "语言",
        "set_language_display": "显示语言",
        "set_language_spell": "语法检查",
        "set_clear": "清除数据",
        "set_about": "关于 [use_com_name]",
        "set_about_ver": "版本 [0] (Chromium [1]) ([2])",
        "set_about_update_checking": "正在检查更新",
        "set_about_update_downloading": "正在下载更新 ([0]%)",
        "set_about_update_waiting": "重启 [use_com_name] 以安装更新",
        "set_about_update_latest": "[use_com_name] 是最新版本",
        "set_about_update_available": "更新可用 ([0])",
        "set_about_update_auto": "在空闲时自动下载更新",
        "set_about_update_error": "更新出现错误 ([0]), 请重新检查更新",
        "set_about_update_btn_update": "更新",
        "set_about_update_insider": "Platinum Insider",
        "set_about_update_insider_info": "你可以在这里收到最近的更新，尝试最新的功能，但也可能会有很多 bug。",
        "set_about_update_btn_insider_join": "加入",
        "set_about_update_btn_insider_exit": "退出",
        "set_about_info_page_sponsor": "赞助",
        "set_about_info_page_privacy": "隐私政策",
        "set_about_info_page_website": "官方网站",
        "set_about_info_page_split": " - ",
        "set_about_info_based_part1": "[use_com_name] 的诞生离不开 ",
        "set_about_info_based_part2": "Chromium",
        "set_about_info_based_part3": " 及其他 ",
        "set_about_info_based_part4": "开源软件",
        "set_about_info_based_part5": "。",
        "set_about_info_copyright_part1": "© [year] ",
        "set_about_info_copyright_part2": "[use_com_author]",
        "set_about_info_copyright_part3": "。保留所有权利。",
        "set_egg": "彩蛋",
        "set_egg_whattheheck": "怎么了，你问我这个字的颜色怎么适配的？\n我用 transform 将原图片向左偏移 1000000 像素，再用 filter 的 drop-shadow 在右边 1000000 像素处显示该图片的投影 (投影可以更改颜色)。",
        "more_restart": "你需要重启你的浏览器来让设置生效。",
        "more_open_tab": "新建标签页",
        "more_open_window": "新建窗口",
        "more_open_window_guest": "新建匿名模式窗口",
        "more_scale": "网页缩放",
        "more_scale_add": "放大",
        "more_scale_minus": "缩小",
        "more_scale_fullscreen": "全屏",
        "more_help_settings": "设置",
        "more_help_about": "关于 [use_com_name]",
        "page_link_open_tab": "在新标签页内打开链接",
        "page_link_open_window": "在新窗口内打开链接",
        "page_link_copy": "复制链接",
        "page_link_qrcode": "为此链接创建二维码",
        "page_select_search": "在网络上搜索 \"[0]\"",
        "page_image_open_tab": "在新标签页打开图片",
        "page_image_save": "将图片另存为",
        "page_image_copy": "复制图片",
        "page_image_copy_link": "复制图片链接",
        "page_image_qrcode": "为此图片创建二维码",
        "page_dev_source": "源代码视图",
        "page_dev_inspect": "开发者工具",
        "share_qrcode": "创建二维码",
        "qrcode_download": "下载",
        "user_title": "用户",
        "user_default": "默认用户",
        "user_syncing": "正在同步数据...",
        "user_idle": "同步已开启",
        "user_error": "同步时遇到了问题: [0]",
        "user_unset": "未设置同步",
        "user_add": "添加用户",
        "user_add_title": "创建一个新用户",
        "user_add_subtitle": "在此输入你的名字或一个标签，例如个人，工作或娱乐。",
        "user_edit_title": "编辑用户信息",
        "user_edit_subtitle": "输入您的新用户名，或上传一个新图片。",
        "user_edit_icon": "更改图片",
        "user_delete_title": "删除此用户",
        "user_delete_subtitle": "这将从本地中永久删除此用户的浏览数据 (例如收藏夹、历史记录和设置)。但是，之前已同步的资料仍可以在其他已登录的设备上查看。",
        "save_started_title": "正在保存此网页",
        "save_started_body": "这可能需要一点时间，您可继续您的工作。我们将会在完成时通知您。",
        "save_finished_title": "保存成功",
        "save_finished_body": "点此查看保存的内容。",
        "save_error_title": "保存失败",
        "save_error_body": "保存时出现错误: [0]。",
        "save_as": "另存为",
        "save_as_pdf": "另存为 PDF 文档",
        "save_print": "打印",
        "closeall_title": "你想关闭所有标签页吗？",
        "fav_open_tab": "在新标签页内打开此页面",
        "fav_open_window": "在新窗口内打开此页面",
        "fav_delete": "删除",
        "fav_new_folder": "新建文件夹",
        "fav_move": "将此项目移动到文件夹",
        "fav_move_root": "根目录",
        "sponsor_title": "赞助",
        "sponsor_body": "此项目由我一人维护，我现在是一个初中生，学习压力很大，光靠 \"用爱发电\" 这个项目是走不远的。所以如果你喜欢此项目或认为此项目对你有帮助的话，欢迎捐赠！",
        "sponsor_store": "或者，去 Microsoft Store 给个好评吧！",
        "fullscreen_tip": "你已进入全屏模式，要退出全屏，请将鼠标移动到顶栏或按下 F11。",
        "fullscreen_html_tip": "按 Esc 退出全屏。",
        "mediacontrol_title": "全局媒体控制",
        "dl_title": "下载管理",
        "dl_open": "打开文件",
        "dl_open_folder": "在文件夹中打开",
        "dl_item": "下载项目 [0]",
        "dl_deleted": "已删除",
        "dl_cancelled": "已取消",
        "dl_paused": "已暂停",
        "dl_error": "错误: [0]",
        "error_title": "加载网页时出了点小故障",
        "error_game": "启动游戏",
        "error_proceed_to_unsafe_page": "继续前往此网页 (不推荐)",
        "errno_unknown": "无法加载 [0]。",
        "errno_-1": "异步 IO 操作尚未完成。",
        "errno_-2": "未指定的错误。",
        "errno_-3": "操作被用户取消。",
        "errno_-4": "函数的参数错误。",
        "errno_-5": "句柄无效。",
        "errno_-6": "找不到文件或目录，此文件或目录可能不存在。",
        "errno_-7": "操作超时。",
        "errno_-8": "文件过大。",
        "errno_-9": "意外错误。",
        "errno_-10": "拒绝访问。",
        "errno_-11": "此功能尚未实现。",
        "errno_-12": "资源不足。",
        "errno_-13": "内存溢出。",
        "errno_-14": "正在上传的文件被意外更改。",
        "errno_-15": "Socket 未连接。",
        "errno_-16": "文件已存在。",
        "errno_-17": "路径或文件名过长。",
        "errno_-18": "磁盘储存空间已满。",
        "errno_-19": "此文件可能包含病毒，已经为你阻止。",
        "errno_-20": "请求被客户端拦截。",
        "errno_-21": "网络已更改。",
        "errno_-22": "请求被你的域管理员所阻止，如要访问，请联系域管理员。",
        "errno_-23": "Socket 已连接。",
        "errno_-24": "ChromeOS 正在强制滚回，请求被阻止。",
        "errno_-25": "上传流因重定向或重试需要重新读取，但是它不支持此操作。",
        "errno_-26": "请求上下文被意外关闭。",
        "errno_-27": "由于跨域政策，请求被阻止。",
        "errno_-29": "请求被系统策略所阻止。",
        "errno_-30": "由于跨域政策，请求被阻止。",
        "errno_-31": "请求被阻止，因为没有 H/2 或 QUIC 会话。",
        "errno_-100": "似乎 [0] 关闭了连接。",
        "errno_-101": "连接已重置。",
        "errno_-102": "连接被拒绝。",
        "errno_-103": "连接已终止。",
        "errno_-104": "连接失败。",
        "errno_-105": "找不到 [0] 的 IP 地址。",
        "errno_-106": "未连接到互联网。",
        "errno_-107": "SSL 协议错误。",
        "errno_-108": "无效的 IP 地址。",
        "errno_-109": "无法到达此 IP 地址。",
        "errno_-110": "需要一个客户端证书来进行 SSL 认证。",
        "errno_-111": "无法建立隧道连接。",
        "errno_-112": "没有已启用的 SSL 协议。",
        "errno_-113": "[0] 使用了不受支持的 SSL 协议。",
        "errno_-114": "[0] 请求了一次重协商。",
        "errno_-115": "代理使用了不受支持的方式进行验证。",
        "errno_-116": "在重协商过程中服务器发送了包含错误的证书。",
        "errno_-117": "服务端证书无效或不存在。",
        "errno_-118": "[0] 的响应时间过长。",
        "errno_-119": "DNS 解析队列过大，请求已取消。",
        "errno_-120": "无法为目标主机建立到 SOCKS 代理服务器的连接。",
        "errno_-121": "SOCKS 代理服务器无法与目标主机建立连接，因为无法到达此主机。",
        "errno_-122": "应用层协议协商失败。",
        "errno_-123": "另一方发送了无重协商的消息。",
        "errno_-124": "WinSock 报告写入的数据多于传输的总数据量。",
        "errno_-125": "另一方无法解压它接收到的 SSL 记录。",
        "errno_-126": "另一方接收到了无效的 SSL Mac。",
        "errno_-127": "代理请求进行验证。",
        "errno_-130": "无法与代理建立连接。",
        "errno_-131": "无法使用强制性代理配置。",
        "errno_-133": "预连接时 Socket 数量达到上限。",
        "errno_-134": "在尝试访问客户端 SSL 证书的私钥被拒绝。",
        "errno_-135": "客户端 SSL 证书不包含私钥。",
        "errno_-136": "HTTPS 代理提供的证书无效。",
        "errno_-137": "名称解析时发生了一个未知错误。",
        "errno_-138": "网络访问被拒绝，请检查你的防火墙设置。",
        "errno_-139": "节流器已取消此请求。此网站可能正遭受 DDoS 攻击。",
        "errno_-141": "无法使用客户端 SSL 证书的私钥为用于客户端证书验证的数据签名。",
        "errno_-142": "数据包过大。",
        "errno_-145": "WebSocket 协议错误。",
        "errno_-147": "无法绑定正在使用的地址。",
        "errno_-148": "操作失败因为 SSL 握手未完成。",
        "errno_-149": "另一方的 SSL 证书的公钥无效。",
        "errno_-150": "证书与内置公钥 PIN 不匹配。",
        "errno_-151": "服务端请求的客户端证书的类型都不受支持。",
        "errno_-153": "SSL 解密失败。",
        "errno_-154": "WebSocketJob 实例数量达到上限。",
        "errno_-156": "重协商时服务端证书发生变动。",
        "errno_-159": "SSL 服务器接收到了一个无法识别的名称。",
        /* 160 - 163 Socket Errors */
        "errno_-164": "客户端证书格式无效。",
        "errno_-166": "DNS 服务器返回了 127.0.53.53 (用于缓解 DNS 冲突)。",
        "errno_-167": "服务端证书格式无效。",
        /* 168 - 169 Cert Transparency */
        "errno_-170": "无法重用连接用于代理验证。",
        /* 171 Cert Transparency */
        "errno_-172": "服务器请求了一个已经过时的 Cipher。",
        "errno_-173": "WebSocket 握手成功。",
        "errno_-176": "缓冲区内没有可用空间。",
        "errno_-177": "客户端证书私钥和服务器的首选项之间没有通用的签名算法。",
        "errno_-178": "TLS 1.3 早期数据被服务器拒绝。",
        "errno_-179": "TLS 1.3 早期数据已发送，但服务器用 TLS 1.2 甚至更早的版本进行恢复。",
        "errno_-180": "TLS 1.3 已启用，但是已协商了一个更低的版本，且服务器指示它支持 TLS 1.3。",
        "errno_-181": "服务器的证书具有与协商的 TLS 密钥交换方法不兼容的 keyUsage 扩展。",
        "errno_-182": "无效的 ECHConfigList。",
        "errno_-183": "ECH 未被协商。",
        "errno_-184": "ECH 回退证书无效。",
        "errno_-200": "你的连接不是私密连接。\n\n证书上的名称与主机名不符，此网站可能被攻击或网站配置错误。",
        "errno_-201": "你的连接不是私密连接。\n\n证书已过期，你的时钟可能有误，或此网站可能没有设置有效的证书。",
        "errno_-202": "你的连接不是私密连接。\n\n此网站的证书不受信任，此网站可能被攻击或网站使用了自签名证书。",
        "errno_-203": "此网站的证书包含错误。",
        "errno_-204": "此网站的证书没有确定其是否被吊销的机制。",
        "errno_-205": "无法检查证书是否被吊销，吊销服务器可能正忙碌或不可用。",
        "errno_-206": "此网站的证书已被吊销。",
        "errno_-207": "此网站的证书无效。",
        "errno_-208": "此网站的证书使用了过时的加密算法进行签名。",
        "errno_-210": "证书内的主机名不唯一。",
        "errno_-211": "证书包含了一个过小的 RSA 密钥。",
        "errno_-212": "证书声明的 DNS 名称违反了名称规定。",
        "errno_-213": "证书有效期过长。",
        "errno_-214": "服务器未提供证书透明度信息。",
        "errno_-215": "证书链接到了一个不受信任的旧 Symantec 根证书。",
        "errno_-217": "已知该证书被设备所有者以外的实体用于拦截。",
        "errno_-218": "此连接使用了过时的 SSL/TLS 版本。",
        "errno_-300": "你所输入的网址有误，请检查你的拼写。",
        "errno_-301": "此 URL scheme 协议不受允许。",
        "errno_-302": "未知的 URL scheme 协议。",
        "errno_-303": "此网站尝试跳转到一个无效的网址。",
        "errno_-310": "重定向次数过多。请尝试清除此网站的 Cookie。",
        "errno_-311": "此网站尝试进行不安全的跳转。",
        "errno_-312": "无法加载带有不安全的端口的网址。",
        "errno_-320": "服务器发送了无效的响应。",
        "errno_-321": "无效的分块传输编码。",
        "errno_-322": "服务器不支持此 HTTP 请求方法。",
        "errno_-323": "代理需要验证。",
        "errno_-324": "服务器未发送任何数据。",
        "errno_-325": "响应数据的 HTTP 消息头过大。",
        "errno_-327": "无法执行 PAC 脚本。",
        "errno_-328": "请求的范围不符合要求。",
        "errno_-329": "用于身份验证的标识无效。",
        "errno_-330": "无法解码响应正文的内容。",
        "errno_-331": "操作无法完成，因为所有网络 IO 都被暂停了。",
        "errno_-332": "未接收到 SYN 回复。",
        "errno_-333": "无法将响应转换为目标编码。",
        "errno_-334": "服务器发送了一个无法识别的 FTP 文件列表。",
        "errno_-336": "没有受支持的代理可用。",
        "errno_-337": "HTTP/2 协议出现错误。",
        "errno_-338": "HTTP 身份验证期间无法建立凭据。",
        "errno_-339": "不受支持的 HTTP 验证方式。",
        "errno_-340": "检测响应的编码时出现错误。",
        "errno_-341": "HTTP 身份验证期间没有可用的 Kerberos 凭据。",
        "errno_-342": "SSPI 或 GSSAPI 返回了一个意外的状态码 (已包含在文档中)。",
        "errno_-343": "未正确设置环境以进行身份验证。",
        "errno_-344": "SSPI 或 GSSAPI 返回了一个意外的状态码 (未包含在文档中)。",
        "errno_-345": "HTTP 响应太大，无法排出。",
        "errno_-346": "HTTP 响应包含了多个 \"Content-Length\" 消息头。",
        "errno_-347": "HTTP/2 消息头不完整。",
        "errno_-348": "没有从 DHCP 接收到任何 PAC URL 配置。",
        "errno_-349": "HTTP 响应包含了多个 \"Content-Disposition\" 消息头。",
        "errno_-350": "HTTP 响应包含了多个 \"Location\" 消息头。",
        "errno_-351": "此 HTTP/2 服务器不处理就拒绝了请求。",
        "errno_-352": "此 HTTP/2 服务器没有回复 Ping。",
        "errno_-354": "HTTP 响应正文的大小与 \"Content-Length\" 不匹配。",
        "errno_-355": "HTTP 响应正文使用了分块编码进行传输，但是没有发送终止的零长度分块。",
        "errno_-356": "QUIC 协议出现错误。",
        "errno_-357": "HTTP 响应消息头被一个文件结束符所截断。",
        "errno_-358": "QUIC 握手失败。",
        "errno_-360": "HTTP/2 版本的传输安全性不足。",
        "errno_-361": "另一方违反了 HTTP/2 流量控制。",
        "errno_-362": "另一方发送了大小不正确的 HTTP/2 帧。",
        "errno_-363": "无法编解码已压缩的 HTTP/2 消息头。",
        "errno_-364": "代理在没有一个有效的客户端 Socket 句柄时请求了一次验证。",
        "errno_-365": "需要 HTTP/1.1。",
        "errno_-366": "需要 HTTP/1.1。",
        "errno_-367": "PAC 脚本已致命终止，必须重新加载。",
        "errno_-370": "无效的 HTTP 响应。",
        "errno_-371": "初始化内容解码失败。",
        "errno_-372": "接收了一个 HTTP/2 RST_STREAM 帧且返回了 NO_ERROR 错误码。",
        "errno_-373": "请求声明的 HTTP/2 推送流不可用。",
        "errno_-375": "HTTP 事务重试次数过多。",
        "errno_-376": "在一个已关闭的流上接收到了一个 HTTP/2 帧。",
        "errno_-377": "客户端拒绝了此 HTTP/2 流。",
        "errno_-378": "请求根据匹配的网址和请求标头声明了推送的 HTTP/2 流，但推送的响应标头与请求不匹配。",
        "errno_-379": "服务器返回了一个非 2xx 的状态码。",
        "errno_-380": "QUIC 连接中提交的证书的根证书未知。",
        "errno_-381": "接收了一个 QUIC GOAWAY 帧但可以其他连接中安全地重试。",
        /* 400 - 413 Cache */
        "errno_-501": "[0] 发送了不安全的响应。",
        "errno_-502": "尝试导入客户端证书失败，因为用户的密钥数据库缺少相应的私钥。",
        "errno_-503": "无法将证书添加到操作系统证书数据库中。",
        "errno_-504": "无效的 Signed Exchange。",
        "errno_-505": "无效的 Web 捆绑包源。",
        "errno_-506": "执行请求的信任令牌协议操作失败",
        "errno_-507": "在处理执行请求的 Trust Tokens 协议操作时，系统能够执行请求的 Trust Tokens 操作，而无需将请求发送到其目标。",
        /* 600 - 607 FTP */
        /* 700 - 714 Cert Manager */
        "errno_-800": "收到了一条格式错误的 DNS 响应。",
        "errno_-801": "DNS 服务器需要 TCP。",
        "errno_-802": "DNS 服务器出错。",
        "errno_-803": "DNS 事务超时。",
        "errno_-804": "DNS 条目未在缓存中找到。",
        "errno_-805": "后缀搜索列表规则阻止解析给定的主机名。",
        "errno_-806": "无法为地址排序。",
        "errno_-808": "无法解析 DoH 服务器的主机名。",
        "errno_-809": "DNS 将该请求标识为不允许进行不安全连接 (http/ws)。",
    },
    "zh-tw": {
        "com_unknown": "抱歉，我們暫時無法在語言檔案中找到此條目的當地語系化文字。",
        "com_name": ((!isDev) ? ((!isPreview) ? ("Platinum") : ("Platinum 預覽版")) : ("Platinum 開發版")),
        "com_author": "Flysoft",
        "com_remove": "移除",
        "com_delete": "删除",
        "com_edit": "編輯",
        "com_ok": "確定",
        "com_cancel": "取消",
        "com_trash": "將檔案移入廢紙簍",
        "com_continue": "繼續",
        "com_pause": "暫停",
        "com_redownload": "重新下載",
        "com_remove_result": "移除下載記錄",
        "com_new_tab": "新索引標籤",
        "com_create_tab": "創建新索引標籤",
        "com_undo": "撤銷",
        "com_redo": "恢復",
        "com_cut": "剪下",
        "com_copy": "複製",
        "com_paste": "貼上",
        "com_paste_text": "貼上 (純文字)",
        "com_selectall": "全選",
        "com_tab_close": "關閉新索引標籤",
        "com_nav_back": "後退",
        "com_nav_forward": "前進",
        "com_nav_refresh": "重新整理",
        "com_nav_stop": "停止加載",
        "com_nav_home": "主頁",
        "com_nav_urlinput": "URL",
        "com_nav_fav_add": "將此網頁添加到我的最愛中",
        "com_nav_fav_remove": "將此網頁從我的最愛中移除",
        "com_nav_more": "更多",
        "com_nav_siteinfo_safe": "連線是安全的，點擊檢視網站資訊",
        "com_nav_siteinfo_unsafe": "您到此網站的連線不是私密連接，點擊檢視網站資訊",
        "com_nav_siteinfo_internal": "您正在查看一個安全的 [use_com_name] 頁面",
        "com_nav_siteinfo_file": "您正在查看一個本地頁面",
        "com_nav_siteinfo_unknown": "此網站的協定未知",
        "com_select_file": "選擇一個檔案",
        "com_whatsnew": "查看新增功能",
        "start_title": "開始",
        "start_settings": "\"開始\" 頁面設定",
        "start_search": "搜尋 Web 或輸入URL",
        "his_title": "歷史記錄",
        "his_all": "全部",
        "his_removemulti_title": "已選擇 [0] 個項目。",
        "ups_title": "[use_com_name] 已更新！",
        "ups_body": "你的瀏覽器已經成功陞級到 [0]。",
        "cl_title": "更新日誌",
        "tetris_title": "俄羅斯方塊",
        "tetris_score": "分數: [0]",
        "tetris_gameover": "按下空白鍵以重新開始",
        "siteinfo_safe": "連線安全\n這意味著資訊會被加密地發送至網站，且不會被攻擊者盜取。(但這並不意味著這個網站是安全的。)",
        "siteinfo_unsafe": "您到此網站的連接不是私密連線\n請勿在此網站上輸入任何機密資訊 (例如密碼或銀行卡)，攻擊者可能會竊取这些資訊。",
        "siteinfo_show_cert": "顯示網站證書",
        "set_title": "設定",
        "set_needrestart_title": "[use_com_name] 需要重啓",
        "set_needrestart_settings_body": "你所更改的設定需要重啓瀏覽器才能生效。\n點此重啓瀏覽器。",
        "set_needrestart_update_body": "更新下載完畢，請重啓瀏覽器來應用更新。\n點此重啓瀏覽器。",
        "set_user": "用戶",
        "set_user_sync": "資料同步",
        "set_user_sync_enable": "啟用同步",
        "set_user_sync_token": "GitHub Access Token",
        "set_user_sync_token_info_part1": "我們需要訪問您的 GitHub Gist 才能開啟同步。請生成一個 ",
        "set_user_sync_token_info_part2": "GitHub Access Token",
        "set_user_sync_token_info_part3": " 並粘貼到上方的輸入框中即可開啟同步。",
        "set_user_other": "其他",
        "set_user_other_desktoplink": "創建快捷方式",
        "set_user_other_edit": "編輯用戶資訊",
        "set_user_other_delete": "删除此用戶",
        "set_homepage": "主頁",
        "set_homepage_start": "開始",
        "set_homepage_start_background": "背景圖片",
        "set_homepage_start_background_unsplash": "從 Unsplash 隨機獲取",
        "set_homepage_start_background_bing": "從必應每日一圖獲取",
        "set_homepage_start_background_pixiv": "Pixiv 上的插畫 (第三方)",
        "set_homepage_start_background_genshin": "原神隨機圖片 (第三方)",
        "set_homepage_start_background_honkai": "崩壞3rd隨機圖片 (第三方)",
        "set_homepage_start_background_mc": "Minecraft 隨機圖片 (第三方)",
        "set_homepage_start_background_url": "從 URL 獲取",
        "set_homepage_start_background_file": "本地檔案",
        "set_homepage_start_background_no": "關閉背景圖片",
        "set_homepage_start_background_info_pixiv_part1": "Pixiv 隨機圖片服務",
        "set_homepage_start_background_info_pixiv_part2": "Lolicon API",
        "set_homepage_start_background_info_horatio_part1": "原神、崩壞3rd、Minecraft 隨機圖片服務",
        "set_homepage_start_background_info_horatio_part2": "HoratioWeb",
        "set_homepage_start_background_info_part1": "由 ",
        "set_homepage_start_background_info_part2": " 提供，",
        "set_homepage_start_background_info_part3": "與 [use_com_author] 沒有任何關係 (注意: API 提供的圖片可能包含二創內容，請謹慎使用)。",
        "set_homepage_start_background_blur": "啟用模糊效果",
        "set_homepage_home": "主頁",
        "set_homepage_homebtn_show": "顯示主頁按鈕",
        "set_homepage_page": "主頁網址",
        "set_homepage_page_start": "使用開始頁面",
        "set_homepage_page_url": "使用自定義 URL",
        "set_appearance": "外觀",
        "set_appearance_overall": "整體外觀",
        "set_appearance_overall_default": "跟隨系統",
        "set_appearance_overall_light": "亮色",
        "set_appearance_overall_dark": "暗色",
        "set_appearance_theme": "主題",
        "set_appearance_visual": "視覺效果",
        "set_appearance_visual_blur": "启用模糊效果",
        "set_appearance_visual_fullblur": "啟用全模糊效果",
        "set_appearance_visual_usebackdrop": "使用系統的模糊效果代替軟件自帶的模糊效果 (實驗)",
        "set_appearance_visual_spotlight": "啟用聚光燈效果 (實驗)",
        "set_appearance_visual_animation": "禁用動畫效果",
        "set_appearance_visual_lowperformance": "啟用流暢模式",
        "set_appearance_visual_lowperformance_info": "去除部分影響效能的效果與動畫，該選項對效能不佳的電腦十分有用。",
        "set_appearance_tcolor": "主題色",
        "set_appearance_tcolor_system": "使用系統主題色",
        "set_appearance_tcolor_theme": "使用主題指定的主題色",
        "set_appearance_tcolor_custom": "使用自定義主題色",
        "set_appearance_behavior": "瀏覽器行為",
        "set_appearance_behavior_askmulti": "關閉包含多個索引標籤的視窗前進行詢問",
        "set_pfm": "效能",
        "set_pfm_sys": "系統",
        "set_pfm_sys_turbo": "啟動加速",
        "set_pfm_sys_turbo_info": "在後臺啟動 [use_com_name] 以更快地打開視窗。",
        "set_pfm_sys_hardwareacceleration": "啟用硬體加速",
        "set_pfm_sleep": "标签页睡眠",
        "set_pfm_sleep_enable": "啟用索引標籤睡眠",
        "set_pfm_sleep_enable_info": "長時間未使用的索引標籤會自動進入睡眠模式，節省 CPU 資源。",
        "set_pfm_sleep_timeout": "當索引標籤未使用多久時，讓索引標籤進入睡眠模式",
        "set_pfm_sleep_timeout_immediately": "立刻",
        "set_pfm_sleep_timeout_1min": "1 分鐘",
        "set_pfm_sleep_timeout_10min": "10 分鐘",
        "set_pfm_sleep_timeout_30min": "30 分鐘",
        "set_pfm_sleep_timeout_1hour": "1 小時",
        "set_pfm_sleep_timeout_2hour": "2 小時",
        "set_language": "語言",
        "set_language_display": "顯示語言",
        "set_language_spell": "語法檢查",
        "set_clear": "清除數據",
        "set_about": "關於 [use_com_name]",
        "set_about_ver": "版本 [0] (Chromium [1]) ([2])",
        "set_about_update_checking": "正在檢查更新",
        "set_about_update_downloading": "正在下載更新 ([0]%)",
        "set_about_update_waiting": "重啓 [use_com_name] 以安裝更新",
        "set_about_update_latest": "[use_com_name] 是最新版本",
        "set_about_update_available": "更新可用 ([0])",
        "set_about_update_auto": "在空閒時自動下載更新",
        "set_about_update_error": "更新出現錯誤 ([0]), 請重新檢查更新",
        "set_about_update_btn_update": "更新",
        "set_about_update_insider": "Platinum Insider",
        "set_about_update_insider_info": "你可以在這裡收到最近的更新，嘗試最新的功能，但也可能會有很多 bug。",
        "set_about_update_btn_insider_join": "加入",
        "set_about_update_btn_insider_exit": "退出",
        "set_about_info_page_sponsor": "贊助",
        "set_about_info_page_privacy": "隱私政策",
        "set_about_info_page_website": "官方網站",
        "set_about_info_page_split": " - ",
        "set_about_info_based_part1": "[use_com_name] 來自 ",
        "set_about_info_based_part2": "Chromium",
        "set_about_info_based_part3": " 開放原始碼專案及其他 ",
        "set_about_info_based_part4": "開放原始碼軟體",
        "set_about_info_based_part5": "。",
        "set_about_info_copyright_part1": "© [year] ",
        "set_about_info_copyright_part2": "[use_com_author]",
        "set_about_info_copyright_part3": "。保留所有權利。",
        "set_egg": "彩蛋",
        "set_egg_whattheheck": "怎麼了，你問我這個字的顏色怎麼適配的？ \n我用 transform 將原圖向左偏移 1000000px，再用 filter 的 drop-shadow 在右邊 1000000px 處顯示該圖片的投影 (投影可以更改顏色)。",
        "more_restart": "你需要重啓你的瀏覽器來讓設定生效。",
        "more_open_tab": "新建索引標籤",
        "more_open_window": "新建視窗",
        "more_open_window_guest": "新建匿名模式視窗",
        "more_scale": "縮放",
        "more_scale_add": "放大",
        "more_scale_minus": "縮小",
        "more_scale_fullscreen": "全屏",
        "more_help_settings": "設定",
        "more_help_about": "關於 [use_com_name]",
        "page_link_open_tab": "在新索引標籤內打開連結",
        "page_link_open_window": "在新視窗內打開連結",
        "page_link_copy": "複製連結",
        "page_link_qrcode": "為此連結創建 QR 碼",
        "page_select_search": "在 Web 上搜尋 \"[0]\"",
        "page_image_open_tab": "在新索引標籤打開圖片",
        "page_image_save": "將圖片另存為",
        "page_image_copy": "複製圖片",
        "page_image_copy_link": "複製圖片連結",
        "page_image_qrcode": "為此圖片創建 QR 碼",
        "page_dev_source": "檢視頁面來源",
        "page_dev_inspect": "開發者工具",
        "share_qrcode": "創建 QR 碼",
        "qrcode_download": "下載",
        "user_title": "用戶",
        "user_default": "默認用戶",
        "user_syncing": "正在同步數據...",
        "user_idle": "同步已開啟",
        "user_error": "同步時遇到了問題: [0]",
        "user_unset": "未設定同步",
        "user_add": "添加新用戶",
        "user_add_title": "創建一個新用戶",
        "user_add_subtitle": "在此輸入你的名字或一個標籤，例如個人，工作或娛樂。",
        "user_edit_title": "編輯資料",
        "user_edit_subtitle": "輸入新的名稱，或上傳一個新圖片。",
        "user_edit_icon": "更改圖片",
        "user_delete_title": "删除此用戶",
        "user_delete_subtitle": "這將從本地中永久删除此用戶的瀏覽數據 (例如我的最愛、歷史記錄和設定)。但是，已同步的資料仍可以在其他已登入的設備上查看。",
        "save_started_title": "正在保存此網頁",
        "save_started_body": "這可能需要一點時間，您可繼續您的工作。 我們將會在完成時通知您。",
        "save_finished_title": "保存成功",
        "save_finished_body": "點此查看剛才保存的內容。",
        "save_error_title": "保存失敗",
        "save_error_body": "保存時出現錯誤: [0]。",
        "save_as": "另存為",
        "save_as_pdf": "另存為 PDF",
        "save_print": "列印",
        "closeall_title": "你想關閉所有索引標籤嗎？",
        "fav_open_tab": "在新索引標籤內打開此頁面",
        "fav_open_window": "在新窗口內打開此頁面",
        "fav_delete": "删除",
        "fav_new_folder": "新建資料夾",
        "fav_move": "將此項目移動到資料夾",
        "fav_move_root": "根",
        "sponsor_title": "贊助",
        "sponsor_body": "此項目由我一人維護，我現在是一個初中生，學習壓力很大，光靠 \" 用愛發電\" 這個項目是走不遠的。 所以如果你喜歡此項目或認為此項目對你有幫助的話，歡迎捐贈！",
        "sponsor_store": "或者，去 Microsoft Store 給個好評吧！",
        "fullscreen_tip": "你已進入全屏模式，要退出全屏，請將滑鼠移動到頂欄或按 F11。",
        "fullscreen_html_tip": "按 Esc 退出全屏。",
        "mediacontrol_title": "全域媒體控制",
        "dl_title": "下載管理",
        "dl_open": "打開檔案",
        "dl_open_folder": "在資料夾中打開",
        "dl_item": "下載項目 [0]",
        "dl_deleted": "已删除",
        "dl_cancelled": "已取消",
        "dl_paused": "已暫停",
        "dl_error": "錯誤: [0]",
        "error_title": "加載網頁時出了點小故障",
        "error_game": "啟動遊戲",
        "error_proceed_to_unsafe_page": "繼續前往此網頁 (不推薦)",
        "errno_unknown": "無法加載 [0]。",
        "errno_-1": "非同步 IO 操作尚未完成。",
        "errno_-2": "未指定的錯誤。",
        "errno_-3": "操作被用戶取消。",
        "errno_-4": "函數的參數錯誤。",
        "errno_-5": "控制碼無效。",
        "errno_-6": "找不到檔案或目錄，此檔案或目錄可能不存在。",
        "errno_-7": "操作超時。",
        "errno_-8": "檔案過大。",
        "errno_-9": "意外錯誤。",
        "errno_-10": "拒絕訪問。",
        "errno_-11": "此功能尚未實現。",
        "errno_-12": "資源不足。",
        "errno_-13": "記憶體溢出。",
        "errno_-14": "正在上傳的檔案被意外更改。",
        "errno_-15": "Socket 未連接。",
        "errno_-16": "檔案已存在。",
        "errno_-17": "路徑或檔名過長。",
        "errno_-18": "磁片儲存空間已滿。",
        "errno_-19": "此檔案可能包含病毒。",
        "errno_-20": "請求被用戶端攔截。",
        "errno_-21": "網絡已更改。",
        "errno_-22": "請求被你的域管理員所封锁，如要訪問，請聯系域管理員。",
        "errno_-23": "Socket 已連接。",
        "errno_-24": "ChromeOS 正在強制滾回，請求被封锁。",
        "errno_-25": "上傳流因重定向或重試需要重新讀取，但是它不支持此操作。",
        "errno_-26": "請求上下文被意外關閉。",
        "errno_-27": "由於跨域政策，請求被封锁。",
        "errno_-29": "請求被系統策略所封锁。",
        "errno_-30": "由於跨域政策，請求被封锁。",
        "errno_-31": "請求被封锁，因為沒有 H/2 或 QUIC 會話。",
        "errno_-100": "似乎 [0] 關閉了連接。",
        "errno_-101": "連接已重置。",
        "errno_-102": "連接被拒絕。",
        "errno_-103": "連接已終止。",
        "errno_-104": "連接失敗。",
        "errno_-105": "找不到 [0] 的 IP 地址。",
        "errno_-106": "未連接到互聯網。",
        "errno_-107": "SSL 協定錯誤。",
        "errno_-108": "無效的 IP 地址。",
        "errno_-109": "無法到達此 IP 地址。",
        "errno_-110": "需要一個用戶端證書來進行 SSL 認證。",
        "errno_-111": "無法建立隧道連接。",
        "errno_-112": "沒有已啟用的 SSL 協定。",
        "errno_-113": "[0] 使用了不受支持的 SSL 協定。",
        "errno_-114": "[0] 請求了一次重協商。",
        "errno_-115": "代理使用了不受支持的管道進行驗證。",
        "errno_-116": "在重協商過程中服務器發送了包含錯誤的證書。",
        "errno_-117": "服務端證書無效或不存在。",
        "errno_-118": "[0] 的回應時間過長。",
        "errno_-119": "DNS 解析隊列過大，請求已取消。",
        "errno_-120": "無法為目標主機建立到 SOCKS 代理伺服器的連接。",
        "errno_-121": "SOCKS 代理伺服器無法與目標主機建立連接，因為無法到達此主機。",
        "errno_-122": "應用層協定協商失敗。",
        "errno_-123": "另一方發送了無重協商的消息。",
        "errno_-124": "WinSock 報告寫入的數據多於傳輸的總數據量。",
        "errno_-125": "另一方無法解壓它接收到的 SSL 記錄。",
        "errno_-126": "另一方接收到了無效的 SSL Mac。",
        "errno_-127": "代理請求進行驗證。",
        "errno_-130": "無法與代理建立連接。",
        "errno_-131": "無法使用強制性代理配寘。",
        "errno_-133": "預連接時 Socket 數量達到上限。",
        "errno_-134": "在嘗試訪問用戶端 SSL 證書的私密金鑰被拒絕。",
        "errno_-135": "用戶端 SSL 證書不包含私密金鑰。",
        "errno_-136": "HTTPS 代理提供的證書無效。",
        "errno_-137": "名稱解析時發生了一個未知錯誤。",
        "errno_-138": "網絡訪問被拒絕，請檢查你的防火牆設定。",
        "errno_-139": "節流器已取消此請求。此網站可能正遭受 DDoS 攻擊。",
        "errno_-141": "無法使用用戶端 SSL 證書的私密金鑰為用於用戶端證書驗證的數據簽名。",
        "errno_-142": "數据包過大。",
        "errno_-145": "WebSocket 協定錯誤。",
        "errno_-147": "無法綁定正在使用的地址。",
        "errno_-148": "操作失敗因為 SSL 握手未完成。",
        "errno_-149": "另一方的 SSL 證書的公開金鑰無效。",
        "errno_-150": "證書與內寘公開金鑰 PIN 不匹配。",
        "errno_-151": "服務端請求的用戶端證書的類型都不受支持。",
        "errno_-153": "SSL 解密失敗。",
        "errno_-154": "WebSocketJob 實例數量達到上限。",
        "errno_-156": "重協商時服務端證書發生變動。",
        "errno_-159": "SSL 服務器接收到了一個無法識別的名稱。",
        /* 160 - 163 Socket Errors */
        "errno_-164": "用戶端證書格式無效。",
        "errno_-166": "DNS 伺服器返回了 127.0.53.53 (用於緩解 DNS 衝突)。",
        "errno_-167": "服務端證書格式無效。",
        /* 168 - 169 Cert Transparency */
        "errno_-170": "無法重用連接用於代理驗證。",
        /* 171 Cert Transparency */
        "errno_-172": "服務器請求了一個已經過時的 Cipher。",
        "errno_-173": "WebSocket 握手成功。",
        "errno_-176": "緩衝區內沒有可用空間。",
        "errno_-177": "用戶端證書私密金鑰和服務器的首選項之間沒有通用的簽名算灋。",
        "errno_-178": "TLS 1.3 早期數據被服務器拒絕。",
        "errno_-179": "TLS 1.3 早期數據已發送，但服務器用 TLS 1.2 甚至更早的版本進行恢復。",
        "errno_-180": "TLS 1.3 已啟用，但是已協商了一個更低的版本，且服務器訓示它支持 TLS 1.3。",
        "errno_-181": "服務器的證書具有與協商的 TLS 金鑰交換方法不相容的keyUsage擴展。",
        "errno_-182": "無效的 ECHConfigList。",
        "errno_-183": "ECH 未被協商。",
        "errno_-184": "ECH 回退證書無效。",
        "errno_-200": "你的連接不是私密連接。\n\n證書上的名稱與主機名不符，此網站可能被攻擊或網站配寘錯誤。",
        "errno_-201": "你的連接不是私密連接。\n\n證書已過期，你的時鐘可能有誤，或此網站可能沒有設定有效的證書。",
        "errno_-202": "你的連接不是私密連接。\n\n此網站的證書不受信任，此網站可能被攻擊或網站使用了自簽名證書。",
        "errno_-203": "此網站的證書包含錯誤。",
        "errno_-204": "此網站的證書沒有確定其是否被吊銷的機制。",
        "errno_-205": "無法檢查證書是否被吊銷，吊銷服務器可能正忙碌或不可用。",
        "errno_-206": "此網站的證書已被吊銷。",
        "errno_-207": "此網站的證書無效。",
        "errno_-208": "此網站的證書使用了過時的加密演算法進行簽名。",
        "errno_-210": "證書內的主機名不唯一。",
        "errno_-211": "證書包含了一個過小的 RSA 金鑰。",
        "errno_-212": "證書聲明的 DNS 名稱違反了名稱規定。",
        "errno_-213": "證書有效期過長。",
        "errno_-214": "服務器未提供證書透明度資訊。",
        "errno_-215": "證書連結到了一個不受信任的舊 Symantec 根證書。",
        "errno_-217": "已知該證書被設備所有者以外的實體用於攔截。",
        "errno_-218": "此連接使用了過時的 SSL/TLS 版本。",
        "errno_-300": "你所輸入的網址有誤，請檢查你的拼寫。",
        "errno_-301": "此 URL scheme 協定不受允許。",
        "errno_-302": "未知的 URL scheme 協定。",
        "errno_-303": "此網站嘗試跳轉到一個無效的網址。",
        "errno_-310": "重定向次數過多。請嘗試清除此網站的 Cookie。",
        "errno_-311": "此網站嘗試進行不安全的跳轉。",
        "errno_-312": "無法加載帶有不安全的埠的網址。",
        "errno_-320": "服務器發送了無效的響應。",
        "errno_-321": "無效的分塊傳輸編碼。",
        "errno_-322": "服務器不支持此 HTTP 請求方法。",
        "errno_-323": "代理需要驗證。",
        "errno_-324": "服務器未發送任何數據。",
        "errno_-325": "響應數據的 HTTP 消息頭過大。",
        "errno_-327": "無法執行 PAC 腳本。",
        "errno_-328": "請求的範圍不符合要求。",
        "errno_-329": "用於身份驗證的標識無效。",
        "errno_-330": "無法解碼響應正文的內容。",
        "errno_-331": "操作無法完成，因為所有網絡 IO 都被暫停了。",
        "errno_-332": "未接收到 SYN 回復。",
        "errno_-333": "無法將響應轉換為目標編碼。",
        "errno_-334": "服務器發送了一個無法識別的 FTP 檔案清單。",
        "errno_-336": "沒有受支持的代理可用。",
        "errno_-337": "HTTP/2 協定出現錯誤。",
        "errno_-338": "HTTP 身份驗證期間無法建立憑據。",
        "errno_-339": "不受支持的 HTTP 驗證管道。",
        "errno_-340": "檢測響應的編碼時出現錯誤。",
        "errno_-341": "HTTP 身份驗證期間沒有可用的 Kerberos 憑據。",
        "errno_-342": "SSPI 或 GSSAPI 返回了一個意外的狀態碼 (已包含在檔案中)。",
        "errno_-343": "未正確設定環境以進行身份驗證。",
        "errno_-344": "SSPI 或 GSSAPI 返回了一個意外的狀態碼 (未包含在檔案中)。",
        "errno_-345": "HTTP 響應太大，無法排出。",
        "errno_-346": "HTTP 響應包含了多個 \"Content-Length\" 消息頭。",
        "errno_-347": "HTTP/2 消息頭不完整。",
        "errno_-348": "沒有從 DHCP 接收到任何 PAC URL 配寘。",
        "errno_-349": "HTTP 響應包含了多個 \"Content-Disposition\" 消息頭。",
        "errno_-350": "HTTP 響應包含了多個 \"Location\" 消息頭。",
        "errno_-351": "此 HTTP/2 服務器不處理就拒絕了請求。",
        "errno_-352": "此 HTTP/2 服務器沒有回復 Ping。",
        "errno_-354": "HTTP 響應正文的大小與 \"Content-Length\" 不匹配。",
        "errno_-355": "HTTP 響應正文使用了分塊編碼進行傳輸，但是沒有發送終止的零長度分塊。",
        "errno_-356": "QUIC 協定出現錯誤。",
        "errno_-357": "HTTP 響應消息頭被一個檔案結束符所截斷。",
        "errno_-358": "QUIC 握手失敗。",
        "errno_-360": "HTTP/2 版本的傳輸安全性不足。",
        "errno_-361": "另一方違反了 HTTP/2 流量控制。",
        "errno_-362": "另一方發送了大小不正確的 HTTP/2 幀。",
        "errno_-363": "無法編解碼已壓縮的 HTTP/2 消息頭。",
        "errno_-364": "代理在沒有一個有效的用戶端 Socket 控制碼時請求了一次驗證。",
        "errno_-365": "需要 HTTP/1.1。",
        "errno_-366": "需要 HTTP/1.1。",
        "errno_-367": "PAC 腳本已致命終止，必須重新加載。",
        "errno_-370": "無效的 HTTP 響應。",
        "errno_-371": "初始化內容解碼失敗。",
        "errno_-372": "接收了一個 HTTP/2 RST_STREAM 幀且返回了 NO_ERROR 錯誤碼。",
        "errno_-373": "請求聲明的 HTTP/2 推送流不可用。",
        "errno_-375": "HTTP 事務重試次數過多。",
        "errno_-376": "在一個已關閉的流上接收到了一個 HTTP/2 幀。",
        "errno_-377": "用戶端拒絕了此 HTTP/2 流。",
        "errno_-378": "請求根據匹配的網址和請求標頭聲明了推送的 HTTP/2 流，但推送的響應標頭與請求不匹配。",
        "errno_-379": "服務器返回了一個非 2xx 的狀態碼。",
        "errno_-380": "QUIC 連接中提交的證書的根證書未知。",
        "errno_-381": "接收了一個 QUIC GOAWAY 幀但可以其他連接中安全地重試。",
        /* 400 - 413 Cache */
        "errno_-501": "[0] 發送了不安全的響應。",
        "errno_-502": "嘗試導入用戶端證書失敗，因為用戶的金鑰資料庫缺少相應的私密金鑰。",
        "errno_-503": "無法將證書添加到作業系統證書資料庫中。",
        "errno_-504": "無效的 Signed Exchange。",
        "errno_-505": "無效的 Web 捆綁包源。",
        "errno_-506": "執行請求的信任權杖協定操作失敗。",
        "errno_-507": "在處理執行請求的 Trust Tokens 協定操作時，系統能够執行請求的 Trust Tokens 操作，而無需將請求發送到其目標。",
        /* 600 - 607 FTP */
        /* 700 - 714 Cert Manager */
        "errno_-800": "收到了一條格式錯誤的 DNS 響應。",
        "errno_-801": "DNS 伺服器需要 TCP。",
        "errno_-802": "DNS 伺服器出錯。",
        "errno_-803": "DNS 事務超時。",
        "errno_-804": "DNS 條目未在緩存中找到。",
        "errno_-805": "尾碼蒐索清單規則封锁解析給定的主機名。",
        "errno_-806": "無法為地址排序。",
        "errno_-808": "無法解析 DoH 服務器的主機名。",
        "errno_-809": "DNS 將該請求標識為不允許進行不安全連接 (http/ws)。",
    },
    "en-us": {
        "com_unknown": "Unknown",
        "com_name": ((!isDev) ? ((!isPreview) ? ("Platinum") : ("Platinum Preview")) : ("Platinum Dev")),
        "com_author": "Flysoft",
        "com_remove": "Remove",
        "com_delete": "Delete",
        "com_edit": "Edit",
        "com_ok": "OK",
        "com_cancel": "Cancel",
        "com_trash": "Trash item",
        "com_continue": "Resume",
        "com_pause": "Pause",
        "com_redownload": "Retry",
        "com_remove_result": "Remove from list",
        "com_new_tab": "New tab",
        "com_create_tab": "Create a new tab",
        "com_undo": "Undo",
        "com_redo": "Redo",
        "com_cut": "Cut",
        "com_copy": "Copy",
        "com_paste": "Paste",
        "com_paste_text": "Paste as plain text",
        "com_selectall": "Select all",
        "com_tab_close": "Close tab",
        "com_nav_back": "Back",
        "com_nav_forward": "Forward",
        "com_nav_refresh": "Refresh",
        "com_nav_stop": "Stop loading",
        "com_nav_home": "Home",
        "com_nav_urlinput": "URL",
        "com_nav_fav_add": "Add this page to favourites",
        "com_nav_fav_remove": "Remove this page from favourites",
        "com_nav_more": "More",
        "com_nav_siteinfo_safe": "Connection is secure, click here to view site information",
        "com_nav_siteinfo_unsafe": "Your connection to this site isn't secure, click here to view site information",
        "com_nav_siteinfo_internal": "You're viewing a secure [use_com_name] page",
        "com_nav_siteinfo_file": "You're viewing a local page",
        "com_nav_siteinfo_unknown": "Unknown protocol",
        "com_select_file": "Select a file",
        "com_whatsnew": "What's new",
        "start_title": "Start",
        "start_settings": "Start page settings",
        "start_search": "Search or enter URL",
        "his_title": "History",
        "his_all": "All",
        "his_removemulti_title": "[0] selected.",
        "ups_title": "[use_com_name] has been updated!",
        "ups_body": "Your browser has been updated to [0].",
        "cl_title": "Changelog",
        "tetris_title": "TETRIS",
        "tetris_score": "Score: [0]",
        "tetris_gameover": "Press Space to restart",
        "siteinfo_safe": "Connection is secure.\nThis means information (such as passwords or bank cards) will be securely sent to this site and cannot be intercepted by attackers. (This doesn't mean that the site itself is secure.)",
        "siteinfo_unsafe": "Your connection to this site is not private.\nDon't enter any sensitive information (such as passwords or bank cards) on this site, because it may be stolen by attackers.",
        "siteinfo_show_cert": "View site certificate",
        "set_title": "Settings",
        "set_needrestart_title": "[use_com_name] needs to restart",
        "set_needrestart_settings_body": "The setting you changed needs to restart [use_com_name] to take effect.\nClick here to restart.",
        "set_needrestart_update_body": "Update files were downloaded. Please restart [use_com_name] to install updates.\nClick here to restart.",
        "set_user": "User",
        "set_user_sync": "Sync",
        "set_user_sync_enable": "Enable Sync",
        "set_user_sync_token": "GitHub Access Token",
        "set_user_sync_token_info_part1": "We need to read and write your GitHub Gist to sync data. Please generate a ",
        "set_user_sync_token_info_part2": "GitHub Access Token",
        "set_user_sync_token_info_part3": " and paste it here.",
        "set_user_other": "Other",
        "set_user_other_desktoplink": "Create desktop shortcut",
        "set_user_other_edit": "Edit user",
        "set_user_other_delete": "Delete this user",
        "set_homepage": "Home",
        "set_homepage_start": "Start Page",
        "set_homepage_start_background": "Background image",
        "set_homepage_start_background_unsplash": "From Unsplash",
        "set_homepage_start_background_bing": "From Bing image of the day",
        "set_homepage_start_background_pixiv": "Pixiv artworks (3rd party)",
        "set_homepage_start_background_genshin": "Genshin Impact images (3rd party)",
        "set_homepage_start_background_honkai": "Honkai Impact 3 images (3rd party)",
        "set_homepage_start_background_mc": "Minecraft images (3rd party)",
        "set_homepage_start_background_url": "From a URL",
        "set_homepage_start_background_file": "From a local file",
        "set_homepage_start_background_no": "No background image",
        "set_homepage_start_background_info_pixiv_part1": "The Pixiv image service",
        "set_homepage_start_background_info_pixiv_part2": "Lolicon API",
        "set_homepage_start_background_info_horatio_part1": "the Genshin Impact, Honkai Impact 3, Minecraft image service",
        "set_homepage_start_background_info_horatio_part2": "HoratioWeb",
        "set_homepage_start_background_info_part1": " is provided by the ",
        "set_homepage_start_background_info_part2": ", ",
        "set_homepage_start_background_info_part3": "[use_com_author] have no relation with these APIs (Warning: The images provided by APIs may contain derivative works).",
        "set_homepage_start_background_blur": "Enable Blur",
        "set_homepage_home": "Home Page",
        "set_homepage_homebtn_show": "Show home button",
        "set_homepage_page": "Homepage URL",
        "set_homepage_page_start": "Start page",
        "set_homepage_page_url": "Use this URL",
        "set_appearance": "Appearance",
        "set_appearance_overall": "Overall appearance",
        "set_appearance_overall_default": "System default",
        "set_appearance_overall_light": "Light",
        "set_appearance_overall_dark": "Dark",
        "set_appearance_theme": "Theme",
        "set_appearance_visual": "Visual effects",
        "set_appearance_visual_blur": "Enable background Blur",
        "set_appearance_visual_fullblur": "Enable Full Blur",
        "set_appearance_visual_usebackdrop": "Use system backdrops instead of Blur (Experimental)",
        "set_appearance_visual_spotlight": "Enable spotlight (Experimental)",
        "set_appearance_visual_animation": "Disable animation",
        "set_appearance_visual_lowperformance": "Enable low-performance mode",
        "set_appearance_visual_lowperformance_info": "Remove some visual effects that may slow down your PC. This is very useful if your PC has a poor performance.",
        "set_appearance_tcolor": "Theme color",
        "set_appearance_tcolor_system": "Use system's color",
        "set_appearance_tcolor_theme": "Use theme's color",
        "set_appearance_tcolor_custom": "Custom theme color",
        "set_appearance_behavior": "Browser behavior",
        "set_appearance_behavior_askmulti": "Ask before closing a window with multiple tabs",
        "set_pfm": "Performance",
        "set_pfm_sys": "System",
        "set_pfm_sys_turbo": "Launch Turbo",
        "set_pfm_sys_turbo_info": "Start [use_com_name] in the background to create window faster.",
        "set_pfm_sys_hardwareacceleration": "Enable hardware acceleration",
        "set_pfm_sleep": "Sleeping Tabs",
        "set_pfm_sleep_enable": "Enable Sleeping Tabs",
        "set_pfm_sleep_enable_info": "Inactive tabs will automatically go to sleep to save CPU resources.",
        "set_pfm_sleep_timeout": "Let inactive tabs go to sleep after the specified amount of time",
        "set_pfm_sleep_timeout_immediately": "Immediately",
        "set_pfm_sleep_timeout_1min": "1 minute",
        "set_pfm_sleep_timeout_10min": "10 minutes",
        "set_pfm_sleep_timeout_30min": "30 minutes",
        "set_pfm_sleep_timeout_1hour": "1 hour",
        "set_pfm_sleep_timeout_2hour": "2 hours",
        "set_language": "Languages",
        "set_language_display": "Display language",
        "set_language_spell": "Check spelling",
        "set_clear": "Reset settings",
        "set_about": "About [use_com_name]",
        "set_about_ver": "Version [0] (Chromium [1]) ([2])",
        "set_about_update_checking": "Checking for updates",
        "set_about_update_downloading": "Downloading updates ([0]%)",
        "set_about_update_waiting": "Everything is OK! Restart [use_com_name] to apply updates.",
        "set_about_update_latest": "[use_com_name] is up to date",
        "set_about_update_available": "Update available ([0])",
        "set_about_update_auto": "Automatically download updates",
        "set_about_update_error": "Update failed ([0]), please try again",
        "set_about_update_btn_update": "Update",
        "set_about_update_insider": "Platinum Insider",
        "set_about_update_insider_info": "You can get the latest features, but there may be many bugs.",
        "set_about_update_btn_insider_join": "Join",
        "set_about_update_btn_insider_exit": "Exit",
        "set_about_info_page_sponsor": "Sponsor",
        "set_about_info_page_privacy": "Privacy Policy",
        "set_about_info_page_website": "Website",
        "set_about_info_page_split": " - ",
        "set_about_info_based_part1": "[use_com_name] is made possible by the ",
        "set_about_info_based_part2": "Chromium",
        "set_about_info_based_part3": " and other ",
        "set_about_info_based_part4": "open source software",
        "set_about_info_based_part5": ".",
        "set_about_info_copyright_part1": "© [year] ",
        "set_about_info_copyright_part2": "[use_com_author]",
        "set_about_info_copyright_part3": ". All rights reserved.",
        "set_egg": "Egg",
        "set_egg_whattheheck": "You want to know how to fit the text color?\nI use transform to the original image to the left by 1000000 pixels, and then use filter's drop-shadow to display the projection of the image at 1000000 pixels on the right (I can change the color of the projection).",
        "more_restart": "You need to restart your browser to make the settings take effect.",
        "more_open_tab": "New tab",
        "more_open_window": "New window",
        "more_open_window_guest": "New anonymous window",
        "more_scale": "Zoom",
        "more_scale_add": "Zoom in",
        "more_scale_minus": "Zoom out",
        "more_scale_fullscreen": "Enter full screen",
        "more_help_settings": "Settings",
        "more_help_about": "About [use_com_name]",
        "page_link_open_tab": "Open link in new tab",
        "page_link_open_window": "Open link in new window",
        "page_link_copy": "Copy link",
        "page_link_qrcode": "Create QR code for this link",
        "page_select_search": "Search the web for \"[0]\"",
        "page_image_open_tab": "Open image in new tab",
        "page_image_save": "Save image as",
        "page_image_copy": "Copy image",
        "page_image_copy_link": "Copy image link",
        "page_image_qrcode": "Create QR code for this image",
        "page_dev_source": "View source",
        "page_dev_inspect": "Inspect",
        "share_qrcode": "Create QR code",
        "qrcode_download": "Download",
        "user_title": "User",
        "user_default": "Default",
        "user_syncing": "Syncing...",
        "user_idle": "Sync is on",
        "user_error": "Error while syncing: [0]",
        "user_unset": "Sync is off",
        "user_add": "Add",
        "user_add_title": "Create a new user",
        "user_add_subtitle": "Add your name or a label such as Personal, Work, or Entertainment.",
        "user_edit_title": "Edit user",
        "user_edit_subtitle": "Enter a new name or upload a image.",
        "user_edit_icon": "Change picture",
        "user_delete_title": "Delete user",
        "user_delete_subtitle": "This will permanently delete the browsing data (such as favorites, history, and settings) locally. And the synced data can still be available for other devices.",
        "save_started_title": "Saving page",
        "save_started_body": "This might take some time to complete, so you can continue to work. We will remind you when we complete.",
        "save_finished_title": "Saved successfully",
        "save_finished_body": "Click here to see the file you saved.",
        "save_error_title": "Failed to save this page",
        "save_error_body": "An error occurred: [0].",
        "save_as": "Save as",
        "save_as_pdf": "Save as PDF",
        "save_print": "Print",
        "closeall_title": "Do you want to close all tabs?",
        "fav_open_tab": "Open in new tab",
        "fav_open_window": "Open in new window",
        "fav_delete": "Delete",
        "fav_new_folder": "Create folder",
        "fav_move": "Move the item to ...",
        "fav_move_root": "Root",
        "sponsor_title": "Sponsor",
        "sponsor_body": "This project is maintained by myself now.\n\nI am now a junior high school student,\nand I'm under a lot of pressure.\n\nIf you like this project or think it is helpful to you,\nyou are welcome to sponsor me!",
        "sponsor_store": "Or you can go to the Microsoft Store and add a five star review!",
        "fullscreen_tip": "To exit fullscreen, move your mouse to top of screen or Press F11.",
        "fullscreen_html_tip": "Press Esc to exit fullscreen.",
        "mediacontrol_title": "Global Media Control",
        "dl_title": "Downloads",
        "dl_open": "Open",
        "dl_open_folder": "Show in folder",
        "dl_item": "Download item [0]",
        "dl_deleted": "Removed",
        "dl_cancelled": "Cancelled",
        "dl_paused": "Paused",
        "dl_error": "Error: [0]",
        "error_title": "This site can't be reached",
        "error_game": "Tetris",
        "error_proceed_to_unsafe_page": "Proceed (Unsafe)",
        "errno_unknown": "Cannot load [0]。",
        "errno_-1": "Asynchronous IO operation is not yet complete.",
        "errno_-2": "Unknown error.",
        "errno_-3": "Operation cancelled by user.",
        "errno_-4": "Invalid argument.",
        "errno_-5": "Invalid handle.",
        "errno_-6": "The file cannot be not found.",
        "errno_-7": "Operation timed out.",
        "errno_-8": "The file is too large.",
        "errno_-9": "Unexpected error.",
        "errno_-10": "Permission to access a resource, other than the network, was denied.",
        "errno_-11": "Unimplemented function.",
        "errno_-12": "There were not enough resources to complete the operation.",
        "errno_-13": "Out of memory.",
        "errno_-14": "The file being uploaded has been changed.",
        "errno_-15": "Socket not connected.",
        "errno_-16": "The file already exists.",
        "errno_-17": "The path name is too long.",
        "errno_-18": "There is no space on the disk.",
        "errno_-19": "This file may contain a virus and we had blocked for you.",
        "errno_-20": "The request was blocked by the client.",
        "errno_-21": "Network changed.",
        "errno_-22": "The request was blocked by the URL block list configured by the domain administrator.",
        "errno_-23": "Socket already connected.",
        "errno_-24": "ChromeOS forced reenrollment check is still pending.",
        "errno_-25": "The upload failed because the upload stream needed to be re-read, due to a retry or a redirect, but the upload stream doesn't support that operation.",
        "errno_-26": "URLRequestContext has been shut down.",
        "errno_-27": "The request failed because the response was delivered along with requirements which are not met ('X-Frame-Options' and 'Content-Security-Policy' ancestor checks and 'Cross-Origin-Resource-Policy', for instance).",
        "errno_-29": "The request was blocked by system policy.",
        "errno_-30": "The request was blocked by a Content Security Policy.",
        "errno_-31": "The request was blocked because of no H/2 or QUIC session.",
        "errno_-100": "[0] unexpectedly closed the connection.",
        "errno_-101": "Connection was reset.",
        "errno_-102": "Connection was refused.",
        "errno_-103": "Connection timed out as a result of not receiving an ACK for data sent.",
        "errno_-104": "Connection attempt failed.",
        "errno_-105": "Cannot resolve the host name.",
        "errno_-106": "No Internet connection.",
        "errno_-107": "SSL protocol error.",
        "errno_-108": "Invalid IP address or port number.",
        "errno_-109": "The IP address is unreachable.",
        "errno_-110": "A client certificate was required for SSL client authentication.",
        "errno_-111": "Cannot establish a tunnel connection through the proxy.",
        "errno_-112": "No SSL protocol versions are enabled.",
        "errno_-113": "[0] used an unsupported SSL protocol version or ciper.",
        "errno_-114": "[0] requested a renegotiation.",
        "errno_-115": "The proxy requested authentication with an unsupported method.",
        "errno_-116": "The server sent a certificate with an error during renegotiation.",
        "errno_-117": "The server certificate is invalid or missing.",
        "errno_-118": "[0] took too long to respond.",
        "errno_-119": "There are too many pending DNS resolves in the queu.",
        "errno_-120": "Failed establishing a connection to the SOCKS proxy server for a target host.",
        "errno_-121": "The SOCKS proxy server failed establishing connection to the target host because that host is unreachable.",
        "errno_-122": "The request to negotiate an alternate protocol failed.",
        "errno_-123": "The peer sent an SSL no_renegotiation alert message.",
        "errno_-124": "WinSock reports more data written than passed.",
        "errno_-125": "The peer sent a fatal decompression_failure alert.",
        "errno_-126": "The peer sent a fatal bad_record_mac alert.",
        "errno_-127": "The proxy requested authentication.",
        "errno_-130": "Could not create a connection to the proxy server.",
        "errno_-131": "A mandatory proxy configuration could not be used.",
        "errno_-133": "We had hit the max socket limit for the socket pool while preconnecting.",
        "errno_-134": "The permission to use the SSL client certificate's private key was denied.",
        "errno_-135": "The SSL client certificate has no private key.",
        "errno_-136": "The certificate presented by the HTTPS Proxy was invalid.",
        "errno_-137": "Name resolution failed.",
        "errno_-138": "Permission to access the network was denied. Please check your firewall settings.",
        "errno_-139": "The request throttler module cancelled this request. The website may be under attack.",
        "errno_-141": "Unable to sign the CertificateVerify data of an SSL client auth handshake with the client certificate's private key.",
        "errno_-142": "The message was too large for the transport.",
        "errno_-145": "WebSocket protocol error.",
        "errno_-147": "Cannot bind an address that is already in use.",
        "errno_-148": "Operation failed because the SSL handshake has not completed.",
        "errno_-149": "The peer's public key is invalid.",
        "errno_-150": "The certificate didn't match the built-in public key pins for the host name.",
        "errno_-151": "Server request for client certificate did not contain any supported types.",
        "errno_-153": "The peer sent a fatal decrypt_error alert.",
        "errno_-154": "There are too many pending WebSocketJob instances.",
        "errno_-156": "The SSL server certificate changed in a renegotiation.",
        "errno_-159": "The SSL server sent a fatal unrecognized_name alert.",
        /* 160 - 163 Socket Errors */
        "errno_-164": "Failed to import a client certificate from the platform store into the SSL library.",
        "errno_-166": "Resolving a hostname to an IP address list included the IPv4 address \"127.0.53.53\".",
        "errno_-167": "The SSL server presented a certificate which could not be decoded.",
        /* 168 - 169 Cert Transparency */
        "errno_-170": "The attempt to reuse a connection to send proxy auth credentials failed.",
        /* 171 Cert Transparency */
        "errno_-172": "The SSL server required an unsupported cipher suite.",
        "errno_-173": "WebSocket is done successfully.",
        "errno_-176": "No socket buffer space is available.",
        "errno_-177": "There were no common signature algorithms between our client certificate private key and the server's preferences.",
        "errno_-178": "TLS 1.3 early data was rejected by the server.",
        "errno_-179": "TLS 1.3 early data was offered, but the server responded with TLS 1.2 or earlier.",
        "errno_-180": "TLS 1.3 was enabled, but a lower version was negotiated and the server returned a value indicating it supported TLS 1.3.",
        "errno_-181": "The server's certificate has a keyUsage extension incompatible with the negotiated TLS key exchange method.",
        "errno_-182": "Invalid ECHConfigList.",
        "errno_-183": "ECH not negotiated.",
        "errno_-184": "ECH fallback cert is invalid.",
        "errno_-200": "The server responded with a certificate whose common name did not match the host name. The website may be misconfigured or be attacked.",
        "errno_-201": "The server responded with a certificate that appears to either not yet be valid or to have expired.  The website may be misconfigured or be attacked.",
        "errno_-202": "The server responded with a certificate that is signed by an authority we don't trust. The website may use a self-signed certificate or be attacked.",
        "errno_-203": "The server responded with a certificate that contains errors.",
        "errno_-204": "The certificate has no mechanism for determining if it is revoked. ",
        "errno_-205": "Revocation information for the security certificate for this site is not available.",
        "errno_-206": "The server responded with a certificate has been revoked.",
        "errno_-207": "The server responded with a certificate that is invalid.",
        "errno_-208": "The server responded with a certificate that is signed using a weak signature algorithm.",
        "errno_-210": "The host name specified in the certificate is not unique.",
        "errno_-211": "The server responded with a certificate that contains a weak key.",
        "errno_-212": "The certificate claimed DNS names that are in violation of name constraints.",
        "errno_-213": "The certificate's validity period is too long.",
        "errno_-214": "The server did not provide Certificate Transparency information.",
        "errno_-215": "The certificate chained to a legacy Symantec root that is no longer trusted.",
        "errno_-217": "The certificate is known to be used for interception by an entity other the device owner.",
        "errno_-218": "The connection uses an obsolete version of SSL/TLS.",
        "errno_-300": "The webpage at [0] might be temporarily down or it may have moved permanently to a new web address.",
        "errno_-301": "The scheme of the URL is disallowed.",
        "errno_-302": "The scheme of the URL is unknown.",
        "errno_-303": "Attempting to load an URL resulted in a redirect to an invalid URL.",
        "errno_-310": "Too many redirects. Please try cleaning Cookies.",
        "errno_-311": "Attempting to load an URL resulted in an unsafe redirect.",
        "errno_-312": "Attempting to load an URL with an unsafe port number.",
        "errno_-320": "[0] sent a invalid response.",
        "errno_-321": "Invalid chunked transfer encoding.",
        "errno_-322": "The server did not support the request method.",
        "errno_-323": "The response was 407 (Proxy Authentication Required).",
        "errno_-324": "[0] closed the connection without sending any data.",
        "errno_-325": "Headers section is too large.",
        "errno_-327": "Cannot evaluate the PAC script.",
        "errno_-328": "The response was 416 (Requested range not satisfiable).",
        "errno_-329": "The identity used for authentication is invalid.",
        "errno_-330": "Content decoding of the response body failed.",
        "errno_-331": "An operation could not be completed because all network IO is suspended.",
        "errno_-332": "SYN reply not received.",
        "errno_-333": "Converting the response to target encoding failed.",
        "errno_-334": "The server sent an unrecognized FTP directory listing.",
        "errno_-336": "There are no supported proxies in the provided list.",
        "errno_-337": "HTTP/2 protocol error.",
        "errno_-338": "Credentials could not be established during HTTP Authentication.",
        "errno_-339": "The HTTP Authentication scheme is unsupported.",
        "errno_-340": "Detecting the encoding of the response failed.",
        "errno_-341": "No Kerberos credentials were available during HTTP Authentication.",
        "errno_-342": "SSPI or GSSAPI returned a status code (documented).",
        "errno_-343": "The environment was not set up correctly for authentication.",
        "errno_-344": "SSPI or GSSAPI returned a status code (undocumented).",
        "errno_-345": "The HTTP response was too big to drain.",
        "errno_-346": "The HTTP response contained multiple distinct \"Content-Length\" headers.",
        "errno_-347": "HTTP/2 headers have been received, but not all of them.",
        "errno_-348": "No PAC URL configuration could be retrieved from DHCP.",
        "errno_-349": "The HTTP response contained multiple \"Content-Disposition\" headers.",
        "errno_-350": "The HTTP response contained multiple \"Location\" headers.",
        "errno_-351": "HTTP/2 server refused the request without processing.",
        "errno_-352": "HTTP/2 server didn't respond to the Ping message.",
        "errno_-354": "The HTTP response body transferred fewer bytes than were advertised by the \"Content-Length\" header when the connection is closed.",
        "errno_-355": "The HTTP response body is transferred with Chunked-Encoding, but the terminating zero-length chunk was never sent when the connection is closed.",
        "errno_-356": "QUIC protocol error.",
        "errno_-357": "The HTTP headers were truncated by an EOF.",
        "errno_-358": "The QUIC crytpo handshake failed.",
        "errno_-360": "Transport security is inadequate for the HTTP/2 version.",
        "errno_-361": "The peer violated HTTP/2 flow control.",
        "errno_-362": "The peer sent an improperly sized HTTP/2 frame.",
        "errno_-363": "Decoding or encoding of compressed HTTP/2 headers failed.",
        "errno_-364": "Proxy auth requested without a valid Client Socket Handle.",
        "errno_-365": "HTTP_1_1_REQUIRED error code received on HTTP/2 session.",
        "errno_-366": "HTTP_1_1_REQUIRED error code received on HTTP/2 session to proxy.",
        "errno_-367": "The PAC script terminated fatally and must be reloaded.",
        "errno_-370": "The server returned an invalid HTTP response.",
        "errno_-371": "Initializing content decoding failed.",
        "errno_-372": "Received HTTP/2 RST_STREAM frame with NO_ERROR error code.",
        "errno_-373": "The pushed stream claimed by the request is no longer available.",
        "errno_-375": "An HTTP transaction was retried too many times due for authentication or invalid certificates.",
        "errno_-376": "Received an HTTP/2 frame on a closed stream.",
        "errno_-377": "Client refused the HTTP/2 stream.",
        "errno_-378": "A pushed HTTP/2 stream was claimed by a request based on matching URL and request headers, but the pushed response headers do not match the request.",
        "errno_-379": "The server returned a non-2xx HTTP response code.",
        "errno_-380": "The certificate presented on a QUIC connection does not chain to a known root.",
        "errno_-381": " A GOAWAY frame has been received indicating that the request has not been processed and is therefore safe to retry on a different connection.",
        /* 400 - 413 Cache */
        "errno_-501": "[0] sent an insecure response.",
        "errno_-502": "An attempt to import a client certificate failed, as the user's key database lacked a corresponding private key.",
        "errno_-503": "An error adding a certificate to the OS certificate database.",
        "errno_-504": "Invalid Signed Exchange.",
        "errno_-505": "Invalid Web Bundle source.",
        "errno_-506": "A Trust Tokens protocol operation-executing request failed.",
        "errno_-507": "When handling a Trust Tokens protocol operation-executing request, the system  was able to execute the request's Trust Tokens operation without sending the request to its destination.",
        /* 600 - 607 FTP */
        /* 700 - 714 Cert Manager */
        "errno_-800": "DNS resolver received a malformed response.",
        "errno_-801": "DNS server requires TCP.",
        "errno_-802": "DNS server failed.",
        "errno_-803": "DNS transaction timed out.",
        "errno_-804": "The entry was not found in cache or other local sources,",
        "errno_-805": "Suffix search list rules prevent resolution of the given host name.",
        "errno_-806": "Failed to sort addresses.",
        "errno_-808": "Failed to resolve the hostname of a DNS-over-HTTPS server.",
        "errno_-809": "DNS identified the request as disallowed for insecure connection (http/ws).",
    },
}
export var _name: string;

export function encode(str: string) {
    return htmlEncode(str).replace(/\n/g, "<br>").replace(/\s/g, "&nbsp;");
}

export function decode(str: string) {
    return htmlDecode(str.replace(/\<br\>/g, "\n"));
}

export function reload(lang: string) {
    _name = lang;
    if (typeof document !== "undefined") {
        if (_name) {
            var texts = document.getElementsByClassName("text");
            for (var i = 0; i < texts.length; i++) {
                const element = <HTMLElement>texts.item(i);
                var domText = element.dataset.text || element.innerHTML;
                if (domText && domText.indexOf("{") != -1 && domText.indexOf("}") != -1) {
                    var domLang = get(domText);
                    element.innerHTML = encode(domLang);
                    element.dataset.text = domText;
                }
            }
            var titles = document.getElementsByClassName("stitle");
            for (var i = 0; i < titles.length; i++) {
                const element = <HTMLElement>titles.item(i);
                var titleText = element.dataset["titletext"] || element.title || element.ariaLabel || element.ariaPlaceholder;
                if (titleText && titleText.indexOf("{") != -1 && titleText.indexOf("}") != -1) {
                    var titleLang = get(titleText);

                    if (element.title) element.title = titleLang;
                    if (element.ariaPlaceholder) element.ariaPlaceholder = titleLang;
                    element.ariaLabel = titleLang;
                    element.dataset["titletext"] = titleText;
                }
            }
        }
        var imgs = document.querySelectorAll("img");
        for (var i = 0; i < imgs.length; i++) {
            imgs.item(i).draggable = false;
        }
    }
}

export function get(msg: string, replace = [], fallback: boolean = true): string {
    if (msg.indexOf("{") != -1 && msg.indexOf("}") != -1) {
        msg = msg.replace("{", "").replace("}", "").replace(/\s+/g, "");
    }
    var data: string = _data[_name][msg];
    if (!data && !fallback) return null;
    if (!data && fallback) data = _data["en-us"][msg];
    if (!data && fallback) data = msg.replace(/_/g, ".");
    for (var i = 0; i < replace.length; i++) {
        data = data.replace("[" + i + "]", replace[i]);
    }
    let date = new Date();
    data = data.replace(/\[year\]/g, date.getFullYear().toString());
    let regexp = /(?<=\[use_)[^}]*(?=\])/;
    let match = data.match(regexp);
    if (match)
        data = data.replace("[use_" + match[0] + "]", get(match[0]));
    return data;
}

export function analyse(sourceLang: string, targetLangs: Array<string>) {
    let result: Record<string, Record<string, Array<string>>> = {};
    for (let i = 0; i < targetLangs.length; i++) {
        let targetLang = targetLangs[i];
        result[targetLang] = {
            missing: [],
            redundant: [],
        }
        for (const item in _data[sourceLang]) {
            if (!_data[targetLang][item]) result[targetLang].missing.push(item);
        }
        for (const item in _data[targetLang]) {
            if (!_data[sourceLang][item]) result[targetLang].redundant.push(item);
        }
    }
    return result;
}